#!/bin/bash
# Close start panel and backdrop

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EWW_DIR="$(dirname "$SCRIPT_DIR")"
EWW_CMD="eww -c $EWW_DIR"

$EWW_CMD close hyfocus-start &
$EWW_CMD close hyfocus-backdrop &
$EWW_CMD update selected-workspaces="" &

echo "ok"
