#!/bin/bash
# Submit challenge answer from button click (reads from challenge-input variable)

EWW_CMD="eww -c /home/sof/dev/forks/hyfocus/eww"

INPUT=$($EWW_CMD get challenge-input)
ANSWER=$($EWW_CMD get challenge-answer)

if [ "$INPUT" = "$ANSWER" ]; then
    # Correct! Stop the session
    hyprctl dispatch hyfocus:stop force &
    $EWW_CMD close hyfocus-challenge &
    $EWW_CMD close hyfocus-backdrop &
    $EWW_CMD update challenge-error="" challenge-problem="" challenge-answer="" challenge-input="" &
else
    # Wrong answer
    $EWW_CMD update challenge-error="Incorrect answer. Try again." &
fi
