#!/bin/bash
# Submit challenge answer

EWW_CMD="eww -c /home/sof/dev/forks/hyfocus/eww"

INPUT=$($EWW_CMD get challenge-input)
ANSWER=$($EWW_CMD get challenge-answer)

if [ "$INPUT" = "$ANSWER" ]; then
    # Correct! Stop the session
    hyprctl dispatch hyfocus:stop force &
    $EWW_CMD close hyfocus-challenge &
    $EWW_CMD update challenge-input="" challenge-error="" challenge-problem="" challenge-answer="" &
else
    # Wrong answer
    $EWW_CMD update challenge-error="Wrong answer, try again" challenge-input="" &
fi

echo "ok"
